# ==========================================================================
# Project:   Crayola
# Copyright: @2011 My Company, Inc.
# ==========================================================================

# Add initial buildfile information here
config :all, :required => [
	"sproutcore/core_foundation",
	"sproutcore/foundation",
	"sproutcore/datastore",
	"sproutcore/statechart"
	],
	:theme => "sproutcore/empty_theme"

